version: "3.7"

services:
  grpc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grpc
    command: >
      /bin/bash -c "
        bash compile_proto.sh &&
        yarn build &&
        yarn start:server
      "
    # restart: always
